# upstream sox not yet ready for stricter clang; runs into
# error: incompatible function pointer types initializing 'sox_format_handler_seek'
c_compiler_version:     # [osx]
  - 15                  # [osx]
cxx_compiler_version:   # [osx]
  - 15                  # [osx]
