{% set name = "sox" %}
{% set version = "14.4.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://sourceforge.net/projects/sox/files/sox/{{ version }}/sox-{{ version }}.tar.gz
  md5: d04fba2d9245e661f245de0577f48a33
  patches:
    # Incorporates changes from https://github.com/dmkrepo/libsox to fix building on VS2015+ on windows
    - patches/0001-Add-Visual-studio-fix-from-dmkrepo-and-flac-support.patch
    # backport https://sourceforge.net/p/sox/code/ci/bb38934e11035c8fab141f70dabda3afdd17da36/
    # kept for completeness to highlight the differences of the fix by torchaudio
    - patches/0002-format-improve-is_seekable-test.patch
    # replaces the above fix, take patch from
    # https://github.com/pytorch/audio/pull/1297
    - patches/0003-Fix-fileobj-I-O-un-deterministic-behavior.patch

build:
  number: 1016
  detect_binary_files_with_prefix: true
  run_exports:
    # https://abi-laboratory.pro/tracker/timeline/sox/
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - cmake
    - ninja
    - make  # [not win]
    - pkg-config
    - {{ compiler('c') }}
  host:
    - libpng
    - zlib
    - xz
    - libsndfile
    - libvorbis
    - libflac
    - libopus
    - speex  # [linux]
    - lame  # [not win]
    - mad  # [not win]

  run:
    - libpng
    - zlib
    - xz
    - lame  # [not win]
    - mad  # [not win]


test:
  commands:
    # shared libs
    - test -f $PREFIX/lib/libsox.so                 # [linux]
    - test -f $PREFIX/lib/libsox.dylib              # [osx]
    - otool -L $PREFIX/lib/libsox.dylib             # [osx]
    - if not exist %LIBRARY_LIB%\libsox.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\libsox.dll exit 1  # [win]

    # absence of static libraries
    - test ! -f $PREFIX/lib/libsox.a                # [unix]
    - test ! -f $PREFIX/lib/libsox_static.a         # [unix]

    # headers
    - test -f $PREFIX/include/sox.h                 # [unix]
    - if not exist %LIBRARY_INC%\sox.h exit 1       # [win]

    # binaries
    - sox --help                                    # [win]
    - sox --help | grep "FILE FORMATS" | grep mp3   # [not win]
    - soxi --help | grep "Usage[:] soxi"            # [not win]

about:
  home: http://sox.sourceforge.net/
  license: GPL-2.0-only
  summary: A cross-platform command line utility that can convert various formats of computer audio files in to other formats.
  license_file: COPYING

extra:
  recipe-maintainers:
    - 183amir
    - alexbw
    - sdvillal
