{% set name = "sox" %}
{% set version = "14.4.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://sourceforge.net/projects/sox/files/sox/{{ version }}/sox-{{ version }}.tar.gz
  md5: d04fba2d9245e661f245de0577f48a33
  patches:
    # Incorporates changes from https://github.com/dmkrepo/libsox to fix building on VS2015+ on windows
    - patches/0001-Add-Visual-studio-fix-from-dmkrepo-and-flac-support.patch

build:
  number: 1015
  detect_binary_files_with_prefix: true
  run_exports:
    # https://abi-laboratory.pro/tracker/timeline/sox/
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - cmake
    - ninja
    - make  # [not win]
    - pkg-config
    - {{ compiler('c') }}
  host:
    - libpng
    - zlib
    - xz
    - libsndfile
    - libvorbis
    - libflac
    - libopus
    - speex  # [linux]
    - lame  # [not win]
    - mad  # [not win]

  run:
    - libpng
    - zlib
    - xz
    - lame  # [not win]
    - mad  # [not win]


test:
  commands:
    - test -e $PREFIX/include/sox.h      # [unix]
    - test -e $PREFIX/lib/libsox_static.a       # [unix]
    - test -e $PREFIX/lib/libsox.so      # [linux]
    - test -e $PREFIX/lib/libsox.dylib   # [osx]
    - otool -L $PREFIX/lib/libsox.dylib  # [osx]
    - sox --help  # [win]
    - sox --help |grep "FILE FORMATS" | grep mp3  # [not win]
    - soxi --help |grep "Usage[:] soxi"  # [not win]

about:
  home: http://sox.sourceforge.net/
  license: GPL-2.0-only
  summary: A cross-platform command line utility that can convert various formats of computer audio files in to other formats.
  license_file: COPYING

extra:
  recipe-maintainers:
    - 183amir
    - alexbw
    - sdvillal
