matrix:
  # default channel anaconda 4 requirements
  - [[LIBPNG_VERSION, '"1.6.22"']]
  # conda-forge channel requirements.
  - [[LIBPNG_VERSION, '"1.6.23"']]
travis:
  secure:
    BINSTAR_TOKEN: wTwKTlN/RcNbFNxJdrYgzBcyf+2TEHzi/YeXfjkhlZYn4j1XTLv4ggOxyvCUToufL2+BURjgc4cq8M7ccNWqq8atduY811yGH46OjaT/QHrOsfNG9+mw+PqS42gzk9sqTOfoTEOUDgLFqLrESUSqmVXckefupWCA6XoLa8QdIJeAuXHJE9ev45GaouVQQMfUr1h4F1/vzBijI73wEGxQwdZJdapOAjZzhLdGAy19tiMMKO6/NhUfNYupFdvicIp6bhC2Uw8usTHtvkkLwLRnjL6zuYoGS+ZBromUmJvYvfpsGYPY9ZaOj5hYfwJek5SLbo0g9Qsavyp4VSGSNChab8985CegTwh11QuVjbi2ISDiIOeBgY0n3kxUlu5D/RryQp+rGoiqa/ZbYXpd/HaX8N3stWt78bFFKhtMXTCBBcYxPUGPwG/PaZjqbKtwqd0RRsAY8j3OZS9IooYT4VUBBPmwudaFCr5au7CHbewwaUCcMCl8fIt3bUOOy0endLvZXvKZdJwziY1kw9VPR/ZcwOijTdIE+DO7MLki8LAvg2rKA0bQoBVWgPZlfj8ixG1C67cBJgCP9RSyP/U2kVLOXhVow3VenRxOL1eiIdBK288j7aEVJDfXinTmgY5f0sgs921y8Fpvng9K6MbVlUlD11Zysru/IOVhNVt1wNfuYqw=
appveyor:
  secure:
    BINSTAR_TOKEN: /XxwAsgp0EItmAhoPSov/h0BtAFNj2BuuEqnhgaP9l7Rw2yLBM1lD+3q4LvpVm3B
